mod_collabora: add simple multi lang support
learnweb/moodle-mod_collabora pull request #24
Opened 2020-09-29 20:13 UTC by grabs

Hi,
I added a simple multi lang support for this plugin.
Since the `loleaflet.html` accepts a `lang` parameter. So we can use the current language to set the interface language of the collabora instance.
Collabora does not accept all lang strings. So I use a constant with accepted strings. Maybe later we can change this into a setting.
Collabora need strings like `en` or `en-us` (note the hyphen). Strings with a wrong second part are also possible which leads to a fallback of the first part. The string `de_comm` which does not exist in collabora would result in `de`.
A not accepted first part, e.g. `yy_abc` will result in an empty page. To prevent this I check the first part of the current language and compare it with the accepted strings list.
Best regards
Andreas

2020-10-01 09:11 UTC, moodlebeuth commented
Hello Ashod,

you have made a lot of code changes. Thanks a lot of your work!

Do you have tested all these settings with moodle moodle group and/or gouping mode too?

@grabs please could you review this patch?

Michael

2020-10-01 09:13 UTC, moodlebeuth commented
Hello Andreas,

I've tested your PR and it works as expected. Thanks for your work!

@Ashod: please could you review this patch?

Michael

2020-10-03 15:55 UTC, Ashod requested changes
Looks good, one minor improvement suggested.

2020-10-03 15:55 UTC, Ashod commented on classes/collabora.php
> +        $systemlang = isset($CFG->lang) ?: 'en';
'en' -> self::FALLBACK_LANG

Seems cleaner to avoid hard-coded value when we have a named const.

2020-10-03 15:59 UTC, Ashod commented
> Hello Ashod,
> 
> you have made a lot of code changes. Thanks a lot of your work!
> 
> Do you have tested all these settings with moodle moodle group and/or gouping mode too?

Hi @moodlebeuth ,

I suspect the above comment was meant for one of my PRs, Michael? 
If so, which one? And what is grouping mode?

Thanks!

2020-10-03 19:32 UTC, merged

2020-10-04 09:01 UTC, moodlebeuth commented
Hi @Ashod: I am sos orry, my fault. I meant #21.